### ISSUE TITLE
Proxy requests to same server fail

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#36]
This does not happen on all servers.

```
[16:59:24.543Z] INFO  API:    Call 'activitypub.proxy.api_query' action
FetchError: request to https://mypod.store/sav/data/profiles/635c00ba709e6d23a82eff92 failed, reason: connect ECONNREFUSED 127.0.1.1:443
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1483:11)
    at ClientRequest.emit (events.js:310:20)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:310:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'system',
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED'
}
```

**Comment by srosset81** [comment]
Solved by using a special Docker configure which redirects the domain name to the Traefik container:

```
    extra_hosts:
      - "mypod.store:172.20.0.10"
```

See how this could be improved
