### ISSUE TITLE
Error when two actors on two Pod providers follow each other

### ISSUE THREAD

**Issue by srosset81** [assemblee-virtuelle/activitypods#47]
The ActivitiesHandlerMixin doesn't handle well distant URL. It also creates a problem when calling activitypub.actor.getProfile.

```
[14:02:20.988Z] ERROR BROKER: MoleculerError: Unable to reach SPARQL endpoint http://localhost:3031/john/query. Error message: Not Found. Query: 
        SELECT ?p ?v
        FROM <http://semapps.org/mirror>
        WHERE {
          <http://localhost:3000/john/data/activities/63d7cdecd7fa7e47dd8f1078> ?p ?v
        }
      
    at throw500 (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/middlewares/index.js:37:9)
    at Service.fetch (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/triplestore/service.js:72:13)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Service.handler (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/triplestore/actions/query.js:40:22)
    at async Service.handler (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/triplestore/actions/countTriplesOfSubject.js:26:21)
    at async Service.handler (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/ldp/services/resource/actions/exist.js:15:17)
    at async Service.handler (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/ldp/services/resource/actions/get.js:85:29)
    at async matchActivity (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/activitypub/utils/matchActivity.js:14:38)
    at async matchActivity (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/activitypub/utils/matchActivity.js:28:43)
    at async Service.activitypub.outbox.posted (/home/tim/Projets/semapps/activitypods/node_modules/@semapps/activitypub/mixins/activities-handler.js:22:17)
    at async Promise.all (index 4) {
  code: 500,
  type: 'INTERNAL_SERVER_ERROR',
  data: { status: 'Server Error', text: 'Unable to reach SPARQL endpoint http://localhost:3031/john/query. Error message: Not Found. Query: \n        SELECT ?p ?v\n        FROM <http://semapps.org/mirror>\n        WHERE {\n          <http://localhost:3000/john/data/activities/63d7cdecd7fa7e47dd8f1078> ?p ?v\n        }\n      ' },
  retryable: false
}
```

Bug identified for project Smarketplace

**Comment by srosset81** [comment]
We must do https://github.com/assemblee-virtuelle/activitypods/issues/34

**Comment by srosset81** [comment]
Work in progress: https://github.com/assemblee-virtuelle/semapps/pull/1110

**Comment by srosset81** [comment]
Done
